# Generated by Django 5.1.1 on 2024-09-26 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('token_uri', models.CharField(max_length=500)),
                ('client_id', models.CharField(max_length=500)),
                ('client_secret', models.CharField(max_length=500)),
                ('scopes', models.TextField()),
                ('user', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=500, null=True)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('organizer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('creator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hangout_link', models.URLField(blank=True, null=True)),
                ('conference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conference_solution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('orderId', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('vectorStoreId', models.CharField(blank=True, max_length=100, null=True)),
                ('google_credentials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendar_api_service.googlecredentials')),
            ],
        ),
    ]
