# Generated by Django 5.1.1 on 2024-09-26 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('calendar_api_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecredentials',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.customuser'),
        ),
    ]
