# Generated by Django 5.1.1 on 2024-09-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
